version: '3'
services:
    db:
        image: postgres:10
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_PASSWORD=${PGPASSWORD}
        networks:
        - internal
    gateway:
        image: localhost:5000/gsm-gateway:0.1.0
        env_file: .env
        ports:
        - "80:80"
        devices:
        - "/dev/serial0:/dev/serial0"
        depends_on:
        - db
        networks:
        - internal
    app:
        image: localhost:5000/verticallabs/canary:0.1.0
        networks:
        - internal
        ports:
        - "80:80"    
networks:
    internal:
        internal: true
