version: '3'
services:
    db:
        image: postgres:10
        ports:
        - "5432:5432"
        environment:
        - POSTGRES_PASSWORD=${PGPASSWORD}
        networks:
        - internal
    gateway:
        image: localhost:5000/gsm-gateway:0.3.0
        env_file: .env
        volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"        
        ports:
        - "80:80"
        devices:
        - "/dev/serial0:/dev/serial0"
        depends_on:
        - db
        networks:
        - internal
    app:
        image: localhost:5000/verticallabs/canary:0.2.0
        environment:
        - "PORT=80"
        networks:
        - internal
        ports:
        - "80:80"    
networks:
    internal:
        internal: true
